import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {connect} from './browser_client.mjs';
const [profile,base,output]=process.argv.slice(2);
await mkdir(output,{recursive:true});
const browser=await connect(profile);
try {
  await browser.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1200,deviceScaleFactor:1,mobile:false});
  await browser.call('Page.navigate',{url:`${base}/reconstruction`});
  await browser.wait("document.querySelector('#start') && !document.querySelector('#start').disabled");
  assert.match(await browser.evaluate("document.querySelector('h1').textContent"),/sobrevive/);
  await browser.screenshot(`${output}/idle.png`);
  await browser.evaluate("document.querySelector('#start').click()");
  await browser.wait("document.querySelector('#status').textContent.includes('Executando')");
  await browser.screenshot(`${output}/running.png`);
  await browser.wait("document.querySelector('#status').textContent.includes('concluída') || document.querySelector('#status').textContent.includes('falhou')",480000);
  const status=await browser.evaluate("document.querySelector('#status').textContent");
  console.log(status);
  assert.match(status,/concluída/);
  assert.equal(await browser.evaluate("document.querySelector('#dna-score').textContent"),'4 / 4');
  assert.equal(await browser.evaluate("document.querySelectorAll('.case').length"),4);
  await browser.screenshot(`${output}/completed.png`);
  const report=await browser.evaluate("fetch('/api/reconstruction/report').then(r=>r.json())");
  assert.equal(report.events.filter(e=>e.kind==='case').length,4);
  await writeFile(`${output}/report.json`,JSON.stringify(report,null,2));
  console.log(JSON.stringify(report.summary));
  await browser.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
  await browser.screenshot(`${output}/mobile.png`);
  assert.equal(browser.errors.length,0,JSON.stringify(browser.errors));
} finally {await browser.close();}
