import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {connect} from './browser_client.mjs';
const [profile,base,output]=process.argv.slice(2);
await mkdir(output,{recursive:true});
const browser=await connect(profile);
try {
  await browser.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1200,deviceScaleFactor:1,mobile:false});
  await browser.call('Page.navigate',{url:`${base}/survival`});
  await browser.wait("document.querySelector('#start') && !document.querySelector('#start').disabled");
  assert.match(await browser.evaluate("document.querySelector('h1').textContent"),/5%/);
  await browser.screenshot(`${output}/idle.png`);
  await browser.evaluate("document.querySelector('#runs').value='3';document.querySelector('#start').click()");
  await browser.wait("document.querySelector('#status').textContent.includes('Executando')");
  await browser.screenshot(`${output}/running.png`);
  await browser.wait("document.querySelector('#status').textContent.includes('concluída') || document.querySelector('#status').textContent.includes('falhou')",180000);
  const status=await browser.evaluate("document.querySelector('#status').textContent");
  assert.match(status,/concluída/,status);
  assert.equal(await browser.evaluate("document.querySelector('#passed').textContent"),'3 / 3');
  assert.equal(await browser.evaluate("document.querySelectorAll('#steps button:not(:disabled)').length"),11);
  await browser.evaluate("document.querySelectorAll('#steps button')[4].click()");
  assert.match(await browser.evaluate("document.querySelector('#object').textContent"),/TRON genesis/);
  await browser.screenshot(`${output}/completed.png`);
  const report=await browser.evaluate("fetch('/api/survival/report').then(r=>r.json())");
  assert.equal(report.events.length,33);
  assert.equal(report.summary.passed,3);
  await writeFile(`${output}/report.json`,JSON.stringify(report,null,2));
  await browser.call('Page.reload');
  await browser.wait("document.querySelector('#passed')?.textContent==='3 / 3'");
  await browser.evaluate("document.querySelector('#trial').value='2';document.querySelector('#trial').dispatchEvent(new Event('change'));document.querySelectorAll('#steps button')[7].click()");
  assert.match(await browser.evaluate("document.querySelector('#facts').textContent"),/20 reconstruções independentes/);
  await browser.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert.equal(await browser.evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
  await browser.screenshot(`${output}/mobile.png`);
  assert.equal(browser.errors.length,0,JSON.stringify(browser.errors));
  console.log(JSON.stringify({status,summary:report.summary,screenshots:output}));
} finally {await browser.close();}
